project:
  type: book

book:
  title: "Enseñar Tecnología en Comunidad. Segunda Edición"
  author: "Greg Wilson y Yanina Bellini Saibene"
  date: "11/20/2022"
  chapters:
    - index.qmd
    - rules.qmd
    - intro.qmd
    - models.qmd
    - memory.qmd
    - architecture.qmd
    # - individual.qmd
    # - process.qmd
    # - pck.qmd
    # - performance.qmd
    # - classroom.qmd
    # - motivation.qmd
    # - online.qmd
    # - exercises.qmd
    - community.qmd
    - events.qmd
    - outreach.qmd
    - paid.qmd
    # - finale.qmd
    # - references.qmd
    # - license.qmd
    # - conduct.qmd
    - joining.qmd
    # - glossary.qmd
    # - meetings.qmd
    # - checklists.qmd
    - conceptmaps.qmd
    # - chunking.qmd

bibliography: bibliography.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
























