project:
  type: book

book:
  title: "Enseñar Tecnología en Comunidad (2e)"
  subtitle: "Cómo crear lecciones que funcionen y construir una comunidad docente alrededor"
  author: "Greg Wilson y Yanina Bellini Saibene"
  date: "2022-2023"
  
  page-footer:
    left: |
      Enseñar Tecnología en Comunidad (2e) fue escrito por 
      Greg Wilson y Yanina Bellini Saibene.
    right: |
      El libro fue construido con <a href="https://quarto.org/">Quarto</a>.
  repo-url: https://github.com/yabellini/t3es2ed
  repo-branch: main
  repo-actions: [edit, issue]    

  sidebar:
    search: true
    
  chapters:
    - index.qmd
    - rules.qmd
    - intro.qmd
    - models.qmd
    - memory.qmd
    - architecture.qmd
    - individual.qmd
    # - process.qmd
    # - pck.qmd
    # - performance.qmd
    - classroom.qmd
    # - motivation.qmd
    # - online.qmd
    # - exercises.qmd
    - community.qmd
    - events.qmd
    - outreach.qmd
    - paid.qmd
    # - finale.qmd
    # - references.qmd
    # - license.qmd
    - conduct.qmd
    - joining.qmd
    # - glossary.qmd
    # - meetings.qmd
    - checklists.qmd
    - conceptmaps.qmd
    - chunking.qmd

bibliography: bibliography.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
























