# Tipos de Eventos {#sec-events}

::: callout-warning
## Segunda edición

Estás leyendo la segunda edición en progreso y en castellano de Enseñar Tecnología en Comunidad (Teaching Tech Together). Este capítulo es actualmente un mero borrador de ideas, y no recomendamos su lectura.
:::

Lunch & Learn session. Tell people to invite their friends. They may not realize how powerful their own networks are. When you get people together, you can share what you're all working on from different departments.

hosted a monthly R user group with the following agenda:

    Intro (3-5 min): We provide an overview about the guest presenter we will host and their presentation topic (always an internal R user that is doing something neat with R that could benefit our R programming community)
    Company Data Science Updates (5 min): We discuss data warehouse and system updates that might impact our internal community
    Package Updates (5-10 min): Here we cover major updates to existing popular packages and we update the audience on new and improved internally developed packages
    Guest Presentation (30-40 min)
    Call for Ideas / Topics to discuss in future meetups (5 min)”

hosted the following types of meetups:

    Training that takes several meetings. The most common are 4 weekly meetings. The introduction to R is the one that is most requested. For face-to-face meetings, universities, research institutes and municipalities will often provide locations with computers. For on-line, R-Ladies Global provides a Zoom account.
    Meetup to complete scholarships to participate in conferences. For this one-day event, we got together and helped write or review scholarship applications to attend important conferences like useR! 
    Metameetups. These events are organized between several chapters of the same country or that share the same language. They last between 1 to 3 hours. Talks or workshops are presented. This type of event was a huge success with the possibility of doing it online.
    Joint meetup with a conference. We have hosted tutorials, conducted tutorials, or given talks about R and/or R-Ladies during particular conferences. There are also social events such as all R-Ladies eating together.
    Meetup – Your first talk. An event where a safe and friendly space is generated for people to practice and deliver their first talk. The talk lasts between 5 to 10 minutes, after which feedback is provided.
    Book club meeting. Weekly or monthly meetings are held where different books related to R and data science are read and discussed (and if they have exercises they are solved together). The pandemic made it possible to organize these events between several chapters because of the online aspect.

### Club de Lectura {#sec-events-bookclub}

El objetivo de un club de lectura es leer, discutir, aprender y poner en común experiencias generadas a partir del libro. Este libro se ha usado para club de lecturas online, con encuentros sincrónicos y con hilos de discusión en redes sociales. Algunos pasos a seguir para su organización.

Paso 1. Definir los objetivos del club

:   La idea es poder analizar cada capítulo, realizar los ejercicios propuestos y generar nuevos aprendizajes y construcciones en comunidad. Reflexionar sobre nuestra práctica educativa a la luz de lo leído, como por ejemplo reconocer recursos ya utilizados e identificar recursos y estrategias que podemos sumar.

Paso 1. Definir los encuentros (cantidad y duración).

:   Decidir frecuencia y duración de los encuentros: ¿Cuántos encuentros?, ¿Con qué frecuencia?, ¿Cuál es la duración adecuada para cada encuentro?. Es probable que la respuesta a estas preguntas sea diferente para cada grupo de personas y si los encuentros son en persona u online. En nuestra experiencia un encuentro semanal de una hora permite tener tiempo para preparse, da continuidad y es más sencillo de acomodar en un agenda apretada.

Paso 2. Definir el calendario de temas

:   Es necesario repartir los capítulos que se verán en cada encuentro: ¿Cuántos capítulos por encuentro?, ¿Leemos también los anexos?. Se pueden agrupar los capítulos y anexos por afinidad temática o bien seguir el orden del libro. Lo importante es tener un calendario predefinido que permita a las personas organizarse. Dos posibles organizaciones:

-   Un capítulo por cada encuentro semanal, con la última semana del mes libre para ponerse al día.

\*Ocho encuentros en total, semanales. Se agrupan los capítulos y los anexos de esta manera.

\<FIXME: agregar tabla de organziación\>

Paso 3. Definir responsabilidades

:   La rotación de los roles de liderazgo generan una experiencia más rica. Algunos roles se deben definir antes de iniciar, por ejemplo, organización del club, presentación de un encuentro, moderación de un encuentro. Las personas que participan pueden ir tomando diferentes roles en cada encuentro y quienes tienen más experiencia pueden invitar y apoyar a otras personas a tomar estos roles.

Paso 4: Configurar la infraestrutura

:   Generar un sitio web con los detalles sobre cómo se hará, por qué, para quién, la dinámica (sincrónico/asincrónico), en qué plataforma (Twitter, Zoom, Slack, Telegram), cómo registrarse, fechas, horarios y temas de los encuentros. Es recomendable una encuesta de feedback anónima para el final de cada encuentro para poder ir mejorando la experiencia del club. Se debe seleccionar un código de conducta.

Paso 5. Difusión.

:   Hay que anunciar el club de lectura para que más personas se enteren que se realizará.Redes sociales (con un hashtag propio), listas de emails, meetups, Slack/Telegram propio y de comunidades amigas. Si se puede, tener comunicaciones periódicas, contar qué pasó en cada encuentro y compartirlo con la comunidad en general, puede alentar a nuevas personas a sumarse al club.

Paso 6. Guía de participación durante el encuentro.

:   Generar un documento compartido (Google Doc/Slides, HackMD) estructurado para cada encuentro con una serie de secciones @sec-shared-notes <FIXME>. Las posibles secciones: Título y Datos generales, preguntas que guiarán la discusión y la charla (ejercicios para romper el hielo, trabajo en grupo, todos contestan, etc), preguntas generales fijas en todos los encuentros, material interesante y lo que viene. En este documento se seleccionan ejercicios de cada capítulo y se resuelven en grupo.

Paso 7. Llevar adelante los encuentros.

:   Los responsables inician la plataforma, dan la bienvenida, recuerdan el código de conducta y dirigen la actividad (chat, documento compartido, diapositivas, salas para grupos, etc). Quien presenta repasa los contenidos y gestiona la discusión. Cuando se cumple el tiempo, se comparte la encuesta anónima y los temas del encuentro siguiente. Si son encuentros sincónicos, online, se deja abierto el zoom y la posibilidad de extendernos en el horario, quienes pueden se quedan. En general quienes participaban se quedaban media hora más.

Paso 8. Darle un cierre memorable.

:   Invitar a autores y/o traductores al encuentro final puede ser un excelente cierre. Si no hablan el mismo idioma contratar a una traductora en vivo permite que cada persona hable en el idioma que se siente más cómoda. Los capítulos de las reglas y porqué enseño se discutieron con la presencia del autor. Se recolectaron opiniones e ideas sobre como mejorar el libro.

Paso 9. Evaluar el club y sistematizar lo aprendido.

:   La encuesta de devolución provee material para evaluar (y mejorar) lo realizado. Ir ajustando cada encuentro con las devoluciones permite mejorar el tipo de actividad y de intercambios. Tener diversas formas de participación (hablado, escrito, en el chat, en el documento compartido, en el Slack) genera un ambiente amigable.
