# Unirse a nuestra comunidad {#sec-joining}

::: callout-warning
## Segunda edición

Estás leyendo la segunda edición en progreso y en castellano de Enseñar Tecnología en Comunidad (Teaching Tech Together). Este capítulo está siendo objeto de una profunda reestructuración y puede resultar confuso o incompleto
:::

El propósito de este capítulo es proponerte una serie de opciones para contribuir a nuestra comunidad junto con recursos que te pueden ser útiles en el camino. Agrupamos las opciones en dos grandes categorías:

-   *usando el libro* donde te contamos como se ha usado el contenido del libro. Esperamos que puedas usar estos ejemplos o bien te sirvan de inspiración y te den ideas de como aprender y enseñar el contenido.

-   *contribuyendo al libro* donde detallamos caminos posibles para ayudarnos a mejorar el libro.

## Usando el libro {#sec-joining-using}

Como se declaró en el Capítulo @sec-intro, todo este material puede distribuirse y reutilizarse libremente bajo la licencia Creative Commons Atribución -- No Comercial 4.0 (@sec-license). Puedes usar la versión en línea en <https://educarencomunidad.tech/> en cualquier clase (gratuita o paga), y puedes citar extractos breves bajo las disposiciones de [uso justo][uso-justo], pero no puedes volver a publicar fragmentos grandes en obras comerciales sin permiso previo.

Este material ha sido usado de muchas maneras, desde charlas de media hora a talleres de varios encuentros semanales presenciales y virtuales.

En la siguiente sección te damos detalles de cada uno de los formatos en los que los autores hemos enseñado este contenido, que cubrimos en cada uno y donde puedes encontrar material de apoyo, como slides y documentos compartidos, ya desarrollado.

### Club de Lectura {#sec-joining-using-bookclub}

El objetivo de un club de lectura es leer, discutir, aprender y poner en común experiencias generadas a partir del libro. Es una buena opción si no hay nadie que pueda enseñar el contenido y hay un grupo de personas interesadas en leer el material. 

Presentamos una guía para organizarlos por medio de diez puntos relevantes. 

Paso 1. Definir los objetivos del club

:   La idea es poder analizar cada capítulo, realizar los ejercicios propuestos y generar nuevos aprendizajes y construcciones en comunidad. Reflexionar sobre nuestra práctica educativa a la luz de lo leído, como por ejemplo reconocer recursos ya utilizados e identificar recursos y estrategias que podemos sumar.  Es un buen momento para definir también el formato.

::: callout-note
## Formato del club

Este contenido se ha usado para club de lecturas en persona, con encuentros sincrónicos online y con hilos de discusión en redes sociales.
:::

Paso 2. Decidir frecuencia y duración de los encuentros.

:    ¿Cuántos encuentros?, ¿Con qué frecuencia?, ¿Cuál es la duración adecuada para cada encuentro?. Es probable que la respuesta a estas preguntas sea diferente para cada grupo de personas y el formato del club. En nuestra experiencia un encuentro semanal de una hora permite tener tiempo para prepararse, da continuidad y es más sencillo de acomodar en un agenda apretada. Puede ser buena idea que cada encuentro sea autocontenido, así no es necesario participar de todos los encuentros.


Paso 3. Definir el calendario de temas

:   Es necesario repartir los capítulos que se verán en cada encuentro. ¿Cuántos capítulos por encuentro?, ¿Leemos también los anexos?. Se pueden agrupar los capítulos y anexos por afinidad temática o bien seguir el orden del libro. Lo importante es tener un calendario predefinido que permita a las personas organizarse. Dos ideas: 

  - Un capítulo por cada encuentro semanal, con la última semana del mes libre para ponerse al día.

  - Ocho encuentros semanales en total. Se agrupan los capítulos y los anexos, por ejemplo, de esta manera:

| Encuentro |  Capítulos  | 
| ---:  | :----------- |
| 1 | Modelos mentales y evaluación formativa. Tipos de Ejercicios |
| 2 | Pericia y memoria. Ejemplos de mapas conceptuales|
| 3 |Arquitectura cognitiva. Aprendizaje Individual|
| 4 |Conocimiento de la pedagogía del contenido y Enseñar como un arte performativo |
| 5 | Un proceso para diseñar lecciones. Motivación y desmotivación|
| 6 | En el salón de clase. Enseñar en línea|
| 7 | Construyendo una comunidad de práctica. Difusión y vinculación. Reuniones, reuniones, reuniones|
| 8 | Las Reglas. Introducción. ¿Por qué enseño?|


Paso 4. Definir responsabilidades

:   Una de las cosas más lindas de estos clubes es encontrarte con otras personas que disfrutan de los mismos temas que vos. Los clubes donde las personas van rotando en los diferentes roles son de los más ricos. Quienes tienen más experiencia pueden invitar y apoyar a las personas en roles nuevos. Antes de iniciar definir quien organiza, presenta y modera en cada encuentro. 

Paso 5. Configurar la infraestrutura

:   Generar un sitio web o foro con los detalles sobre cómo se hará, por qué, para quién, la dinámica (sincrónico/asincrónico), dónde (lugar físico o plataforma online), cómo registrarse, fechas, horarios y temas de los encuentros. Es recomendable una encuesta de feedback anónima para el final de cada encuentro. Seleccionar un código de conducta y el proceso para reforzarlo.


Paso 6. Difusión

:   Hay que anunciar el club de lectura en redes sociales (con un hashtag propio), listas de emails, newsletter propio y de comunidades amigas. Si se puede, tener comunicaciones periódicas, contar qué pasó en cada encuentro y compartirlo con la comunidad en general, puede alentar a nuevas personas a sumarse al club. 

Paso 7. Guía de participación durante el encuentro

:   Generar un documento compartido (Google Doc/Slides, HackMD) estructurado para cada encuentro con una serie de secciones (ver @sec-classroom-notetaking). Las posibles secciones:  Título y Datos generales, preguntas que guiarán la discusión y la charla (ejercicios para romper el hielo, trabajo en grupo, todos contestan, etc.), preguntas generales fijas en todos los encuentros, material interesante y lo que viene.

Paso 8. Llevar adelante los encuentros

:   Los responsables inician la plataforma, dan la bienvenida,  recuerdan el código de conducta y dirigen la actividad (chat, documento compartido, diapositivas, salas para grupos, orden para hablar, etc).  Quien presenta repasa los contenidos y gestiona la discusión. Cuando se cumple el tiempo, se comparte la encuesta anónima (si es presencial se puede usar las notas adhesivas @sec-classroom-sticky-notes) y los temas del encuentro siguiente. Si son encuentros sincrónicos y online, se puede dejar abierta la videollamada para extender el horario y quienes pueden siguen compartiendo.

Paso 9. Darle un cierre memorable

:   Invitar a autores y/o traductores al encuentro final puede ser un excelente cierre. Si no hablan el mismo idioma contratar a una traductora en vivo permite que cada persona hable en el idioma que se siente más cómoda.  También es un buen momento para seleccionar el próximo libro.

Paso 10. Evaluar el club y sistematizar lo aprendido

:   La encuesta de devolución provee material para evaluar (y mejorar) lo realizado. Ir ajustando cada encuentro con las devoluciones permite  mejorar el tipo de actividad y de intercambios. Tener diversas formas de participación (hablado, escrito, en el chat, en el documento compartido, en el Slack, con notas adhesivas) genera un ambiente amigable.

::: callout-warning
## TODO Yani!
Tengo que gregar link a las secciones de notas compartidas, feedback y notas adhesivas.
:::


### Cursos largos

Llamamos cursos largos a los talleres de 8 a 16 horas de clase. Esta versión del curso se divide en diez lecciones donde se puede cubrir gran parte de los capítulos @sec-models a @sec-process, @sec-performance, y @sec-motivation. Greg a enseñado la versión de ocho horas más de 30 veces desde 2017 para compañías, bibliotecas y organizaciones de software libre. Yanina ha enseñado la versión de 12 y 16 horas más de 10 veces desde 2021, en español y online para comunidades de práctica, compañías, instituciones de investigación y universidades públicas. 

Esta lista resume los objetivos de aprendizaje de cada lección.

::: callout-warning
## TODO Yani!
Chequear bien que estos sean los capítulos correctos y si hay alguno más que agregar.
:::

Lección 1. Introducción y Personas

:   1. Resumir cuatro objetivos clave de esta formación.
2. Explicar cómo y por qué esta formación prepara a las personas para ser “paramédicos educativos”.
3. Explicar qué son las personas o estudiantes tipo y para qué sirven.
4. Describir los cuatro elementos que debe tener toda persona tipo.
5. Crear estudiantes tipo.
6. Resumir las lecciones de manera que resulten entendibles y atractivas para determinadas personas tipo.

Lección 2. Modelos mentales

:   1. Describir las diferencias entre estudiantes principiantes, competentes y expertos/as.
2. Explicar qué es un modelo mental y por qué no necesita ser completo ni correcto para ser útil.
3. Explicar cómo la falta de un modelo mental afecta el aprendizaje de las personas principiantes y por qué el objetivo de las lecciones para principiantes debe ser ayudarles a construir un modelo mental.
4. Explicar cómo el docente puede saber si alguien tiene un modelo mental funcional.
5. Explicar qué es un mapa conceptual y qué elementos debe tener.
6. Describir cinco maneras en que los mapas conceptuales pueden ser utilizados para planificar, enseñar y evaluar lecciones.
7. Crear mapas conceptuales.
8. Describir 5 estrategias para trabajar con estudiantes de distintos niveles.

::: callout-tip
## Recortando contenido
Para la versión de ocho horas, el objetivo 4 se pueden quitar de la lección.
:::

Lección 3. Carga Cognitiva

:   1. Explicar la diferencia entre la memoria a largo plazo y a corto plazo y describir el ciclo de recuperación/codificación.
2. Describir cómo se procesa, integra y almacena la información visual y auditiva.
3. Resumir las conclusiones de Benner et al sobre los modos de aprendizaje (visual + habla, visual + texto, visual + habla + texto).
4. Definir los tres tipos de carga cognitiva e identificar correctamente ejemplos de cada uno.
5. Explicar que implicancias tiene la teoría de la carga cognitiva para el diseñar y enseñar lecciones.
6. Explicar qué es un problema de Parsons y cómo su eficacia puede basarse en la teoría de la carga cognitiva.
7. Crear Problemas de Parsons y explicar cuándo y cómo deben o no deben utilizarse.

Lección 4. Capacidad Cognitiva

:   1. Explicar qué es "siete más menos dos" (capacidad de la memoria a corto plazo) y qué implica para diseñar y enseñar lecciones.
2. Explicar como los mapas conceptuales pueden ayudar a manejar la capacidad cognitiva.
3. Explicar qué es un ejemplo desvanecido y cómo su eficacia puede basarse en la capacidad limitada de la memoria a corto plazo.
4. Identificar qué tipo de carga cognitiva reducen los problemas desvanecidos.
5. Crear ejercicios con ejemplos desvanecidos y explicar cuándo y cómo deben o no utilizarse.

::: callout-tip
## Recortando contenido
Para la versión de ocho horas, los objetivos 2 y 4 se pueden quitar de la lección.
:::

Lección 5.Crítica - Devolución - Feedback

:   1. Describir las principales diferencias entre el material didáctico estático y la presentación dinámica de las clases, así como el papel de la improvisación en esta última.
2. Explicar tres estrategias para obtener feedback que son útiles para mejorar nuestra enseñanza.
3. Explicar las características de una crítica constructiva.
4. Describir los elementos de una rubrica básica para dar feedback sobre la enseñanza.
5. Explicar qué es la demostración (y programación) en vivo.
6. Explicar los cuatro pasos que debe dar un instructor cada vez que comete un error durante una demostración en vivo delante de una clase.
7. Criticar de forma constructiva presentaciones de clases grabadas y en directo.
8. Identificar y utilizar tres herramientas (notas adhesivas, ticket de salida, uno arriba-uno abajo) para solicitar feedback a los estudiantes. 

::: callout-tip
## Recortando contenido
Para la versión de ocho horas, los objetivos 2,3,5 y 8 se pueden quitar de la lección.
:::

Lección 6.Evaluación

:   1. Definir los términos "evaluación formativa" y "evaluación sumativa" y explicar las diferentes funciones de cada una.
2. Explicar por qué y cómo las evaluaciones formativas deben identificar conceptos erróneos.
3. Describir tres maneras en que los docentes pueden determinar qué conceptos erróneos buscar.
4. Explicar los objetivos complementarios de las evaluaciones formativas para docentes y estudiantes.
5. Explicar qué es la instrucción entre pares, por qué es eficaz y los requisitos para que tenga éxito.
6. Describir el papel de la evaluación sumativa y las características de las evaluaciones sumativas eficaces.
7. Describir el proceso de diseño inverso de una lección. 
8. Crear peguntas de opciones múltiples efectivas.

::: callout-tip
## Recortando contenido
Para la versión de ocho horas, el objetivo 8 se pueden quitar de la lección.
:::

Lección 7.Motivación

:   1. Describir la diferencia entre motivación intrínseca y extrínseca.
2. Resumir tres factores principales de motivación y desmotivación de estudiantes adultos neurotípicos.
3. Definir el término "falso principiante", explicarlo en términos de modelos mentales y explicar los desafíos especiales que los falsos principiantes presentan en la enseñanza.
4. Explicar los peligros de la pre-evaluación y como se relaciona con la motivación.
5. Describir que acciones se pueden tomar como docente para contribuir a la inclusión en clase.
6. Explicar el papel de los escenarios y los juegos de rol en la adquisición de habilidades de persona aliada.
7. Describir y justificar los pasos que debe dar un/a docente si tiene que expulsar a un/a estudiante de su clase.

::: callout-tip
## Recortando contenido
Para la versión de ocho horas, los objetivos 3, 4 y 5 se pueden quitar de la lección.
:::

Lección 8.Aprendizaje

:   1. Explicar la diferencia entre aprendizaje activo y pasivo y dar dos razones de por qué el primero es más eficaz.
2. Enumerar seis estrategias que los estudiantes pueden utilizar para acelerar su aprendizaje
3. Justificar al menos dos de las estrategias mencionadas en función de las ideas introducidas en esta formación.

::: callout-tip
## Recortando contenido
Para la versión de ocho horas, el objetivo 3 se pueden quitar de la lección.
:::

Lección 9.Preparándote para Enseñar

:   1. Describir y resumir las técnicas para que la enseñanza interactiva en línea sea más eficaz.
2. Describir dos métodos para garantizar que la atención se distribuye equitativamente entre los participantes de la clase y explicar por qué es importante.
3. Preparar un inicio de clase que genere un ambiente positivo, incluyendo tu presentación.
4. Escribir objetivos de aprendizajes claros y determinar como se pueden evaluar.

::: callout-tip
## Recortando contenido
Para la versión de ocho horas, el objetivo 3 y 4 se pueden quitar de la lección.
:::

Lección 10. Mitos Educativos y Reglas para enseñar

:   1. Identificar varios mitos comunes sobre la educación y el aprendizaje.
2. Mencionar varias ideas sobre la educación y el aprendizaje que se encuentran en revisión.
3. Reflexionar sobre realizar una buena enseñanza.
4. Identificar fuentes de información donde seguir aprendiendo.

::: callout-tip
## Recortando contenido
Para la versión de ocho horas, los objetivos 2 a 4 se pueden quitar de la lección.
:::

#### Formato del curso

Este curso puede dictarse con diferentes configuraciones.  Este cronograma de ejemplo corresponde a un curso de doce horas con tres encuentros de cuatro horas cada uno.  Es recomendable espaciar los encuentros, con al menos un día entre cada uno.  Se puede enseñar en persona, en formato híbrido u online. Se recomienda que la cantidad de participantes no sea mayor a 25 personas.

|Día 1|  Ejemplo horario a la mañana|        
|:---:|:-----------------------------------|
|  09:00  |Bienvenida ¿Qué debe esperar de este taller?            |
|  09:15  |Introducción. Personas tipo. Modelos Metales. ¿Cómo aprenden las personas? ¿Cómo podemos ayudar a los novatos a convertirse en practicantes competentes? | 
|  10:30  |Pausa de la mañana           | 
|  10:45  |Experiencia e instrucción ¿La experiencia en la materia convierte a alguien en un gran docente? ¿En qué nos diferenciamos instructores de estudiantes y cómo afecta esto a nuestra enseñanza?           |
|  11:30  | Memoria y carga cognitiva ¿Qué es la carga cognitiva y cómo afecta al aprendizaje?, ¿Cómo podemos diseñar la enseñanza para trabajar con, en lugar de contra, las limitaciones de la memoria?          | 
|  12:15  | Desarrollar la habilidad con la retroalimentación ¿Cómo puedo obtener la retroalimentación de los alumnos? ¿Cómo puedo utilizar esta retroalimentación para mejorar mi enseñanza? |
|  13:00: | Fin del primer día |

|Día 2| Ejemplo horario a la tarde |
|:---:|:-----------------------------------|
|13.00| Bienvenida, consultas día anterior.|
|13:30| Motivación y desmotivación ¿Por qué es importante la motivación? ¿Cómo podemos crear un entorno motivador para los alumnos?|
|14:35| Equidad, inclusión y accesibilidad ¿Por qué son importantes la equidad, la inclusión y la accesibilidad? ¿Qué puedo hacer para mejorar la equidad, la inclusión y la accesibilidad en mi taller? |
|15:15 | Pausa de la tarde|
|15:30 | La enseñanza es una habilidad ¿Cómo puedo mejorar mi enseñanza?|
|16:30 | Recapitulación y deberes ¿Qué hemos aprendido hasta ahora? ¿Qué hay que hacer para preparar la siguiente parte del taller?|
|16:50 | Cierre del día|


|Día 3|  Ejemplo horario a la mañana|        
|:---:|:-----------------------------------|
|09:00 |Bienvenida ¿Qué hemos aprendido hasta ahora?¿En qué nos centraremos hoy?|
|09:15 |Interacción. La codificación en vivo es una habilidad ¿Por qué enseñamos a programar utilizando la codificación participativa en vivo?|
|09:50 |Preparación para enseñar ¿Cómo debo prepararme para enseñar?|
|10:25 |Pausa de la mañana |
|10:35 |Codificación en vivo y feedback. Más práctica de codificación en vivo ¿Cómo cambió tu enseñanza en respuesta a la retroalimentación?|
|11:15 |Trabajar con su equipo ¿Cuáles son los retos de gestionar un aula heterogénea? Enseñando en equipo.|
|11:25 |Pausa|
|11:35 |Mitos en la educación. Las reglas para enseñar.|
|12:10 |¿Cómo se utilizan las prácticas de enseñanza que hemos aprendido?|
|12:40 |Conclusión. ¿Qué podemos mejorar en esta formación?|
|12:50 |Encuesta posterior a la formación|
|13:00 |Cierre día 3.|


::: callout-note
## Material complementario

Si quieres enseñar el libro utilizando alguno de los formatos de cursos largos, el curso [Enseñando Tecnología en Comunidad. Consejos prácticos para enseñar aplicando la ciencia del aprendizaje y la enseñanza.](https://yabellini.github.io/t3es/) tiene todo el material en español para un taller de doce horas y [Teaching Tech Together](https://third-bit.com/t3/) tiene todo el material en inglés para un taller de 8 horas, que incluye una propuesta que re acomoda los contenidos de las lecciones.

:::

### Cursos cortos

Es posible crear cursos cortos con una duración de entre una hora y media y tres horas. Se pueden dar online de forma sincrónica o en persona. Yanina impartió estos cursos cortos más de 20 veces desde 2020. 

el objetivo es crear conciencia de la existencia de buenas prácticas básicas para manejo de espacios de intercambio de conocimiento sincrónico y proveer un momento donde experimentar estas buenas prácticas en primera persona durante el taller.

El objetivo de este formato es *introducir* buenas prácticas básicas para manejo de espacios de intercambio de conocimiento sincrónico, ya sea de forma online o presencial y proveer el momento donde experimentar estas buenas prácticas en primera persona durante el taller. 

::: callout-tip
## Haciendo lo que predicamos

Todos los detalles del encuentro, empezando por el registro hasta el pedido de devolución antes de finalizar el curso, pasando por la ejecución del mismo, son una demostración de las estrategias mencionadas en este libro y que pueden ser adoptadas o adaptadas a cualquier intercambio de saberes que suceda interactuando en simultáneo con una audiencia.

:::


Los conceptos pedagógicos que se introducen son:

-   Diseño del espacio de intercambio de saberes pensando en la audiencia objetivo (personas tipo)
-   Mapas conceptuales para el diseño de lecciones y evaluación.
-   Evaluación formativa diagnóstica cada 10-15 minutos para determinar si la audiencia sigue lo explicado y corregir en el momento explicación y contenido.
-   Participación en un documento compartido colaborativo para tomar notas, resolver evaluaciones formativas, compartir material.
-   Herramientas pedagógicas rápidas basadas en evidencia y fáciles de implementar en entornos online, hibridos y presenciales.
-   Como pedir y dar devoluciones efectivas.
-   Compartir fuentes de las cuales seguir aprendiendo y expandiendo prácticas pedagógicas

[Aqui se pueden encontrar un ejemplo de los materiales utilizados en español](https://yabellini.netlify.app/courses/intro-abc-online/).

### Encuentro sincónico de hora y media

Nuevamente el objetivo es crear conciencia de la existencia de buenas prácticas básicas para manejo de espacios de intercambio de conocimiento sincrónico y proveer un momento donde experimentar estas buenas prácticas en primera persona durante el taller.

Los conceptos pedagógicos que se introducen son:

-   Diseño del evento pensando en la audiencia objetivo.
-   Mapas conceptuales.
-   Evaluación formativa diagnóstica para determinar entendimiento y corregir en el momento la explicación y el contenido.
-   Uso de un documento compartido colaborativo para tomar notas, resolver evaluaciones formativas, compartir material.
-   Herramientas pedagógicas rápidas basadas en evidencia y fáciles de implementar en entornos en línea, híbridos y presenciales.
-   Como pedir devoluciones efectivas.
-   Compartir fuentes de las cuales seguir aprendiendo y expandiendo prácticas pedagógicas

Yanina impartió este taller con este formato 10 veces durante 2020. [Aqui se pueden encontrar un ejemplo de los materiales utilizados en español](https://yabellini.netlify.app/courses/introalabc_corto/).





### En persona {#sec-joining-using-inperson}

Las personas que participan están físicamente en el mismo lugar. Cuando necesitan practicar cómo enseñar en pequeños grupos, parte de la clase o toda la clase va a habitaciones cercanas. Cada participante usa su propia tableta o computadora portátil para ver material en línea durante la clase y para tomar notas compartidas (@sec-classroom-notetaking), y usa lápiz y papel o pizarras para otros ejercicios. Las preguntas y la discusión se hacen en voz alta.

Si estás enseñando en este formato, debes usar notas adhesivas como indicadores de estado para que puedas ver quién necesita ayuda, quién tiene preguntas y quién está listo/a para seguir adelante (@sec-classroom-sticky-notes). También debes usarlos para distribuir la atención, para que todo el curso obtenga tu atención y tiempo de forma justa, como tarjetas de actas para alentar a tus estudiantes a reflexionar sobre lo que acaban de aprender y para darte retroalimentación procesable mientras todavía tienes tiempo para actuar en consecuencia.

### Formato híbrido {#sec-joining-using-hybrid}

En este formato, entre 10 a 40 estudiantes se juntan en 2 a 6 grupos de 4 a 12 personas, pero esos grupos están distribuidos geográficamente. Cada grupo usa una cámara y un micrófono para conectarse a la videollamada, en lugar de que cada persona esté en la llamada por separado. Un buen audio es más importante que un buen video en ambas direcciones: una voz sin imágenes (como la radio) es mucho más fácil de entender que las imágenes sin narrativa, y quienes enseñan no necesitan ver a las personas para responder preguntas, siempre y cuando esas preguntas se puedan escuchar con claridad. Dicho esto, si una lección no es accesible, entonces no es útil (@sec-motivation-accessibility): proporcionar texto descriptivo es una ayuda cuando la calidad del audio es deficiente, e incluso si el audio es bueno resulta importante para aquellas personas con dificultades auditivas.

Toda la clase toma notas compartidas (@sec-classroom-notetaking), y también usa las notas compartidas para hacer y responder preguntas. Tener varias decenas de personas tratando de hablar en una llamada no funciona bien, así que en la mayoría de las sesiones el/la docente habla y sus estudiantes responden a través del chat de la video llamada o de la herramienta para tomar notas.

### En línea de forma individual {#sec-joining-using-online}

La extensión natural de estar en línea en grupos es estar en línea en forma individual. Al igual que con los grupos en línea, el/la docente hablará la mayoría de las veces y los/las estudiantes participarán principalmente a través del chat de texto. También en este caso, y siempre teniendo en cuenta los aspectos de accesibilidad, un buen audio es más importante que un buen video, y quienes participan deberían usar el chat de texto para indicar que quieren hablar (@sec-meetings).

Tener participantes en línea individualmente hace que sea más difícil dibujar y compartir mapas conceptuales (@sec-memory-exercises) o dar retroalimentación sobre la enseñanza (@sec-performance-exercises). Por lo tanto, quienes enseñen deberán confiar más en el uso de ejercicios con resultados escritos que se puedan poner en las notas compartidas, como por ejemplo, dar una devolución sobre videos de personas enseñando.

### Multi-semana en línea {#sec-joining-using-multiweek}

#### Clases de una hora {#sec-joining-using-multiweek-onehour}

La clase se reúne todas las semanas durante una hora a través de videoconferencia. Cada reunión puede realizarse dos veces para acomodar las zonas horarias y los horarios de los/las estudiantes. Los/las participantes toman notas compartidas como se describió anteriormente para las clases grupales en línea, para publicar tareas en línea entre clases y para comentar sobre el trabajo de los demás. En la práctica, los comentarios son relativamente raros: la gente prefiere discutir el material en las reuniones semanales.

Este fue el primer formato que Greg utilizó pero ya no lo recomienda. Mientras que extender la clase les da a las personas tiempo para reflexionar y abordar ejercicios más extensos, también aumenta en gran medida las probabilidades de que tengan que abandonar debido a otras demandas de su tiempo.

#### Encuentros de medias jornadas {#sec-joining-using-multiweek-hours}

##### Cuatro encuentros de cuatro horas

El grupo de entre 12 a 26 personas realiza uno o dos encuentros semanales, durante cuatro o dos semanas de forma sincrónica on-line durante cuatro horas. Todo el material del curso está disponible en un sitio web con anterioridad. Si Hay dos clases semanales se deja al menos un día entre cada encuentro.

La clase está estructurada con presentación de contenido con participación activa de los estudiantes por medio de notas compartidas y el chat de la plataforma de videoconferencia. También hay resolución de ejercicios grupales al finalizar de explicar un grupo de temas o conceptos. Se usan documentos compartidos y una reflexión grupal general luego de cada ejercitación. Todos los grupos comparten, al menos una vez, el resultado de sus ejercicios grupales durante los encuentros sincrónicos.

Se les permite a los estudiantes seleccionar si quieren mantener los grupos de un encuentro a otro o prefieren cambiarlos para conocer a mas personas que están tomando el curso.

Este formato tiene la ventaja de dar tiempo para reflexionar y repasar el material entre las clases, pero se mantiene lo suficientemente concentrado en el tiempo para que no intervenga tanto en la rutina de las personas, llevandolas a abandonar. Yanina ha enseñado este material utilizando este formato con muy buenos resultados.

#### Dos encuentros de entre 4.5 horas

##### Antes de empezar

La clase consta de dos sesiones de 4,5 horas en días consecutivos. Unos días antes de empezar, envío a los participantes un recordatorio con los detalles de la videoconferencia, un par de lecturas breves y una invitación a un documento de Google para tomar notas en común. Les pido que añadan una o dos líneas sobre sí mismos al documento antes de que empiece la clase, tanto a modo de introducción como para asegurarme de que tienen permiso para editar el documento.

##### Durante la clase

Suelo tener entre media docena y dos docenas de alumnos a la vez. Si algunos de ellos están en el mismo lugar, les pido que compartan una cámara web y un micrófono de sala de reuniones decente (los micrófonos integrados en los portátiles no son buenos para las conversaciones en grupo), pero todos deben estar en el documento de Google.

Todos están silenciados por defecto. Si alguien quiere hacer una pregunta, puede escribirla en el canal de chat de la videoconferencia o indicar que quiere hablar y anular el silencio cuando le llame. (Permitir ambos modos ayuda a sentirse más cómodas a las personas que se sienten tímidas o que necesitan más tiempo para redactar una pregunta). Utilizamos salas de descanso para debates en grupos pequeños y ejercicios de enseñanza entre iguales. Funcionan bastante bien, aunque es fácil que los grupos pierdan la noción del tiempo.

Los alumnos hacen ejercicios cada 10-30 minutos. Yo pego una lista de nombres en el documento compartido; ellos escriben sus respuestas debajo de sus nombres para no tropezar con los cursores de los demás. También pueden pegar imágenes de cosas como mapas conceptuales; es un poco torpe, pero funciona sorprendentemente bien. También pueden compartir la pantalla con el resto de la clase siempre que quieran demostrar algo, lo cual es tan útil que he empezado a hacerlo también en las clases presenciales de programación.

Al final, pido a los alumnos que hagan un recordatorio en el calendario dentro de un mes para enviarme un correo y decirme lo que aún recuerdan o les ha parecido útil. Alrededor del 20% de ellos envía ese mensaje, y es un indicador útil sobre lo que hay que seguir enseñando y lo que hay que dejar de lado porque no ha tenido impacto.




### ¿Qué enseñamos en cada formato?

En dos jornadas completas (16 horas de curso) se puede cubrir gran parte de los capítulos @sec-models a @sec-process, @sec-performance, y @sec-motivation.

También se puede hacer en una jornada completa o dos medias jornadas (8 horas de curso), en ese caso, estos son los objetivos de aprendizaje


En el caso de los talleres de tres horas, tenemos dos talleres diferentes.

#### Introducción a enseñar

**Objetivo**: Introducir buenas prácticas básicas basadas en evidencia para el manejo de espacios de intercambio de conocimiento presencial (por ejemplo, clase, seminario, taller o charla) o remoto, (por ejemplo, clases sincrónicas usando plataformas de videoconferencia remotas). Cada detalle del taller, empezando por el formulario de registro hasta el pedido de devolución cuando termina el taller, pasando por la ejecución del mismo, son una demostración de estrategias que pueden ser adoptadas o adaptadas a cualquier tarea docente que sucede interactuando en simultáneo con una audiencia.

Durante este taller: \* Mostraremos como contactar y preparar a tu audiencia para sumarse a una clase o evento sincrónico ("la previa") \* Manejaremos un evento remoto a través de Zoom que mantendrá a una audiencia participando activamente durante tres horas. \* Veremos ejemplos de cómo crear un ambiente positivo para nuestra audiencia \* Tendremos una introducción a conceptos pedagógicos de:

-   Diseño de la clase o evento pensando en la audiencia que va a estar recibiendo el material (estudiantes/personas tipo)

-   Uso de mapas conceptuales

-   Evaluación formativa diagnóstica cada para saber si tu audiencia sigue lo que explicas y corregir sobre la marcha cuando detectes que algo no es claro para la mayoría

-   Participación en un documento conjunto colaborativo para tomar notas o resolver evaluaciones formativas

-   Otras herramientas pedagógicas rápidas basadas en evidencia y fáciles de implementar

-   Pedido de devolución a tu audiencia luego de cada clase y cómo dar devoluciones efectivas

-   Compartiremos fuentes de las cuales seguir aprendiendo prácticas pedagógicas

#### Cómo enseñar a programar

Introducir técnicas y buenas prácticas para diseñar tus cursos de programación y evaluar a tus estudiantes.

Durante este taller:

-   Mostraremos cómo diseñar tus cursos de programación de una manera eficiente y productiva.

-   Hablaremos de la utilidad de la revisión entre pares y la importancia de recibir feedback. Discutiremos cómo implementar estas prácticas.

-   Presentaremos diferentes tipos de evaluación y ejercicios posibles. Por ejemplo: problemas de Parsons, Completar los espacios en blancos, etc.

-   Haremos un recorrido por las buenas prácticas de programación y las formas de promover su uso entre tus estudiantes.

-   Presentaremos la práctica de Códificación en vivo (*Live Coding*). Veremos ejemplos prácticos que ayudarán a reconocer detalles a tener en cuenta a la hora de llevarla a cabo.

-   Durante todo el taller ilustraremos los conceptos presentados usando ejemplos de uso en diferentes lenguajes de programación.

### ¿Quién puede enseñar este material?

El club de lectura es una buena forma de tener una enseñanza entre pares, para un grupo de personas que están interesadas en trabajar sobre el material.

Parte de este material se utilizó en el entrenamiento de instructores de The Carpentries y RStudio (ahora Posit), por lo que las personas que están certificadas como instructores de estos programas son una opción razonable para enseñar el material del libro porque les ha sido enseñado y lo han estado aplicando en su tarea docente.

The Carpentries también forma *trainers*, que son las personas que forman a los instructores. Personas certificadas como *trainers* tienen un conocimiento más detallado de las prácticas pedagógicas presentadas en el libro y la experiencia de haber formado personas en estos temas.

## Contribuyendo al libro {#sec-joining-contributing}

Esperamos que elijas ayudarnos a mejorar este libro. Las contribuciones de todo tipo son bienvenidas, desde sugerencias para mejoras hasta erratas y nuevo material. Todas las personas que contribuyan deben cumplir con nuestro Código de Conducta (@sec-conduct); al enviar tu trabajo, aceptas que pueda incorporarse tanto en forma original como editada y que pueda ser publicado bajo la misma licencia que el resto de este material (@sec-license).

Si tu material es incorporado, te agregaremos a los agradecimientos (@sec-intro-acknowledgments) a menos que solicites lo contrario.  Algunas ideas sobre como aportar al libro:


Empieza de a poco.

:   Arregla un error tipográfico, aclara la redacción de un ejercicio, corrige o actualiza una cita, o sugiere un mejor ejemplo o analogía para ilustrar algún punto.

Únete a la conversación.

:   Mira los *issues* y los cambios propuestos por otras personas y añádeles tus comentarios. A menudo es posible mejorar las mejoras, y es una buena manera de presentarte a la comunidad y hacer nuevas amistades. Las etiquetas *"Beginner-Friendly"* (apto para principiantes en inglés), *"Work in Progress"* (trabajo en progreso en inglés) y *"Help Wanted"* (se busca ayuda en inglés) son buenos *issues* para emepzar y unirte a la conversación.

Discute, luego edita.

:   Si quieres proponer un gran cambio, como reorganizar o dividir un capítulo completo, por favor, completa un *issue* que describa tu propuesta y tu razonamiento y etiquétalo como *"Addition"* (agregar en inglés), *"Correction"* (corrección en inglés) ó *"Discussion"* (discusión en inglés). Te alentamos a que agregues comentarios a estos *issues* para que toda la discusión sobre *qué* y *por qué* esté abierta y se pueda archivar. Si se acepta la propuesta, el trabajo real puede dividirse en varios problemas o cambios más pequeños que se pueden abordar de forma independiente.

Traduce.

:   Si quieres traducir este material a otro idioma, por favor genera un *issue* que indique a que idioma quieres realizar la traducción. Te recomendamos que sea un trabajo que realices entre varias personas, con diferentes roles como traducir y revisar y editar. Como guía general, ten en cuenta estos puntos: a) utiliza una voz conversacional en lugar de una voz formal o académica, b) si corresponde, especifique qué dialecto o variante regional de la lengua se está utilizando, c) intenta ser neutral en cuanto al género, d) intenta ser idiomático.

Contanos como usaste el libro

:   Siempre nos gusta escuchar cómo se ha usado este material. Puedes enviarnos un mail o completar un issue contando, cómo y dónde lo usaste y como te fue usándolo. Seguramente tienes ideas para mejorar el material del libro, te agradeceremos que nos compartas esas ideas.

Dibuja mapas conceptuales

:   Si has generado mapas conceptuales para tus lecciones, cursos o talleres y quieres compartirlos, *siempre* agradecemos el aporte de más mapas conceptuales para nuestra colección.

Comparte tus personas

:   Si describiste las personas tipo para tus lecciones o cursos y quieres compartirlos, considera agregarlos a nuestra colección.

